workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 60
    environment:
      android_signing:
        - upload
      #groups:
        #- firebase_credentials
      vars:
        PACKAGE_NAME: "io.codemagic.karlapp"        
      flutter: 3.38.5
      xcode: 26      
    scripts:
      - name: Set up local.properties
        script: | 
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: | 
          flutter pub get
      - name: Flutter analyze
        script: | 
          flutter analyze
      - name: Flutter unit tests
        script: | 
          flutter test
        ignore_failure: true
      - name: Build APK with Flutter
        script: | 
          #BUILD_NUMBER=$(($(google-play get-latest-build-number --package-name "$PACKAGE_NAME" --tracks="$GOOGLE_PLAY_TRACK") + 1))      
          flutter build apk --release \
            --build-name=1.0.$BUILD_NUMBER \
            --build-number=$BUILD_NUMBER
    artifacts:
      #- build/**/outputs/**/*.apk
      - build/app/outputs/flutter-apk/*.apk       # perfect, no duplicates
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log
    publishing:

      email:
        recipients:
          - karl.suhajda@yahoo.com
        notify:
          success: true
          failure: false
           
      #firebase:   #Alter once connected to Firebase 
        #firebase_service_account: $FIREBASE_SERVICE_ACCOUNT    
        #android:
      
         #app_id: 1:961817617668:android:5a1b442cd079b63840dc51 
            
         #groups: 
          # - androidTesters
      